oqtopus-team/oqtopus-cloud

- .github/workflows/labeler.yaml
- .gitmessage
- .vscode/settings.json
- docs/en/developer_guidelines/index.md
- docs/ja/developer_guidelines/index.md
- Add automatic labeling
- Add commit message guidelines
> ci:add labeler

- backend/Makefile
- backend/oqtopus_cloud/provider/conf.py
- backend/oqtopus_cloud/provider/lambda_function.py
- backend/oqtopus_cloud/user/conf.py
- backend/oqtopus_cloud/user/lambda_function.py
- poetry.lock
- pyproject.toml
- terraform/service/modules/api-server/main.tf
add cors setting via environent value
add lambda environment
> refactor: add cors setting via environent value

- backend/oqtopus_cloud/provider/routers/tasks.py
- backend/oqtopus_cloud/user/routers/devices.py
- backend/oqtopus_cloud/user/routers/results.py
- backend/oqtopus_cloud/user/routers/tasks.py
refactor: Convert code that uses legacy SQLAlchemy API to version 2.0.
> refactor: Convert code that uses legacy SQLAlchemy API to version 2.0

- README.md
The readthedocs URL in README.md is incorrect.
The correct address is https://oqtopus-cloud.readthedocs.io/
> docs: fix readthedocs URL

- backend/oas/provider/openapi.yaml
- backend/oas/provider/root.yaml
- backend/oqtopus_cloud/provider/routers/devices.py
- backend/oqtopus_cloud/provider/routers/results.py
- backend/oqtopus_cloud/provider/routers/tasks.py
- docs/en/architecture/sequence_diagram.md
- docs/ja/architecture/sequence_diagram.md
- docs/oas/provider/openapi.yaml
- runnbooks/provider/tasks/get-task.yaml
- runnbooks/provider/tasks/get-tasks.yaml
Since the API Gateways on the user side and provider side have been separated, there is no longer any duplication. Also, from a RESTful perspective, this is the hierarchy where resources should be, so the "internal" hierarchy feels strange. Therefore, the "internal" hierarchy is deleted from the provider side OAS.
> refactor: delete of internal

- docs/en/index.md
- docs/ja/index.md
- The link from https://oqtopus-cloud.readthedocs.io/latest/ to the Japanese page is https://oqtopus-cloud.readthedocs.io/ja/. The correct link is https://oqtopus-cloud.readthedocs.io/latest/ja/ 
- The link from https://oqtopus-cloud.readthedocs.io/latest/ja/ to the Japanese page is https://oqtopus-cloud.readthedocs.io/latest/jp/. The correct link is https://oqtopus-cloud.readthedocs.io/latest/ja/
> docs: fix readthedocs link

- docs/en/architecture/sequence_diagram.md
- docs/ja/architecture/sequence_diagram.md
Following the deletion of GET /tasks/unfetched, the en and jp documents in sequence_diagram.md were revised, but there were some inconsistencies, so I correct them myself.
> docs: Fix sequence_diagram.md to match en and jp documents

- backend/oas/provider/openapi.yaml
- backend/oas/provider/paths/jobs.yaml
- backend/oas/provider/root.yaml
- backend/oas/provider/schemas/jobs.yaml
- backend/oqtopus_cloud/provider/routers/jobs.py
- backend/oqtopus_cloud/provider/schemas/devices.py
- backend/oqtopus_cloud/provider/schemas/jobs.py
- backend/tests/oqtopus_cloud/provider/routers/test_jobs.py
- docs/oas/provider/openapi.yaml
- docs/oas/user/openapi.yaml
#273 (internal)
This PR introduces new Provider API endpoint for updating quantum job info.
With this feature, quantum devices can update the result or reason of failure of their jobs.
>tests/oqtopus_cloud/provider/routers/test_devices.py::test_update_device_pending_jobs PASSED [ 11%]
tests/oqtopus_cloud/provider/routers/test_devices.py::test_update_device_status_available PASSED [ 22%]
tests/oqtopus_cloud/provider/routers/test_devices.py::test_update_device_status_not_available PASSED [ 33%]
tests/oqtopus_cloud/provider/routers/test_jobs.py::test_get_jobs PASSED  [ 44%]
tests/oqtopus_cloud/provider/routers/test_jobs.py::test_get_job PASSED   [ 55%]
tests/oqtopus_cloud/provider/routers/test_jobs.py::test_update_job PASSED [ 66%]
tests/oqtopus_cloud/provider/routers/test_jobs.py::test_updat …
> feat: Add endpoint for updating job info.

- docs/terraform_modules/api-server/README.md
- terraform/service/modules/api-server/README.md
- terraform/service/modules/api-server/main.tf
- terraform/service/modules/api-server/variables.tf
- terraform/service/oqtopus-dev/main.tf
https://github.com/FujitsuResearch/QuantumCloudPlatform/issues/279
This PR updates terraform configuration of the API service, enabling Cognito authorizer pluggable.
This PR does not bring any breaking change, existing cloud stack would work without any modification.
> feat: Make  API Authorizer pluggable

- backend/oas/provider/openapi.yaml
- backend/oas/provider/paths/devices.yaml
- backend/oas/provider/paths/hello.yaml
- backend/oas/provider/paths/jobs.yaml
- backend/oas/provider/schemas/error.yaml
- backend/oas/user/openapi.yaml
- backend/oas/user/paths/devices.yaml
- backend/oas/user/paths/jobs.yaml
- backend/oas/user/schemas/error.yaml
- backend/oqtopus_cloud/provider/routers/devices.py
- backend/oqtopus_cloud/provider/routers/jobs.py
- backend/oqtopus_cloud/provider/schemas/error.py
- backend/oqtopus_cloud/provider/schemas/errors.py
- backend/oqtopus_cloud/user/routers/devices.py
- backend/oqtopus_cloud/user/routers/jobs.py
- backend/oqtopus_cloud/user/schemas/error.py
- backend/oqtopus_cloud/user/schemas/errors.py
- backend/tests/oqtopus_cloud/user/routers/test_jobs.py
https://github.com/FujitsuResearch/QuantumCloudPlatform/issues/283
- refactor OpenAPI specifications and error response schemas in `errors.py` 
- I think it is better to use the schema generated from `datamodel-code-generator`, but it does not seem to support status codes, so I use the response model of `errors.py` written in the manual.
see CI result
> refactor: unify OpenAPI responses from 'details' or 'message' to 'message'

- .github/workflows/python-ci.yaml
#78 
Issue with not finding `.coverage-common`: Explicitly set the `include-hidden-files` option to true.
Issue with not finding `pyproject.toml`: Add a checkout step for the repository.
> fix: #78 coverage action error

- backend/db/init/03.insert_job.sql
```diff
- '{\'code\': \'todo\'}'
+ '{"program": ["todo"]}'
```
It will fix
```
{"level":"INFO","location":"get_jobs:146","message":"error: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)","timestamp":"2025-02-06 12:41:50,128+0900","service":"user-api","correlation_id":"local-correlation-id","fastapi":{"path":"/devices","route":"/devices","method":"GET"}}
```
> error: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)","timestamp
and
```
{"level":"WARNING","location":"get_jobs:140","message":"Failed to decode job_info: 1 validation error for JobInfo\nprogram\n  Field required [type=missing, input_value={'code': 'todo'}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.10/v/missing","timestamp":"2025-02-06 …
```
> fix: `job_info` json format

- backend/oqtopus_cloud/provider/routers/jobs.py
- backend/tests/oqtopus_cloud/provider/routers/test_jobs.py
- https://github.com/FujitsuResearch/QuantumCloudPlatform/issues/308
The logic for calculating job_info and status has been revised.
Now, the job status is automatically updated only when setting the job result.
In all other cases, the updated status must be explicitly specified using the `overwrite_status` property, including for `failed` states.
> fix: job info message and result

- backend/oas/user/openapi.yaml
- backend/oas/user/paths/jobs.yaml
https://github.com/FujitsuResearch/QuantumCloudPlatform/issues/293
Removed the "sampling" character from the OAS operationID because it still had the old specification
See CI logs
> refactor: remove "sampling" from operationId

- backend/oqtopus_cloud/provider/routers/jobs.py
- backend/oqtopus_cloud/user/routers/jobs.py
- backend/tests/oqtopus_cloud/provider/routers/test_jobs.py
- backend/tests/oqtopus_cloud/user/routers/test_jobs.py
https://github.com/FujitsuResearch/QuantumCloudPlatform/issues/295
When GET /jobs is called, it returned a 404 error if only one job is abnormal and the others are normal.
It should return other normal jobs in this case.
- if jobs is abnormal, it was ignored and record to log, and return other normal jobs
- add test case reproduce this situation
See CI logs
> Bugfix/#295 GET /jobs return normal jobs and ignore abnormal jobs

- backend/oas/provider/openapi.yaml
- backend/oas/provider/schemas/jobs.yaml
- backend/oas/user/openapi.yaml
- backend/oas/user/schemas/jobs.yaml
- backend/oqtopus_cloud/provider/routers/jobs.py
- backend/oqtopus_cloud/provider/schemas/jobs.py
- backend/oqtopus_cloud/user/routers/jobs.py
- backend/oqtopus_cloud/user/schemas/jobs.py
- backend/tests/oqtopus_cloud/user/routers/test_jobs.py
- docs/oas/provider/openapi.yaml
- docs/oas/user/openapi.yaml
https://github.com/FujitsuResearch/QuantumCloudPlatform/issues/292
`created_at` and `updated_at` should not be returned to user or provider because they are system internal information to record when tables are updated.
- remove `created_at` and `updated_at` fields from `JobDef` and `GetJobsResponse` schema in OAS
- modify related python codes and tests
See CI logs
> Feature/#292 remove "created_at" and "updated_at" from GET /jobs

- backend/oqtopus_cloud/admin/routers/devices.py
* https://github.com/FujitsuResearch/QuantumCloudPlatform/issues/341
> fix: handle None input in ensure_timezone function

- backend/oqtopus_cloud/lambda_auth/lambda_function.py
* https://github.com/FujitsuResearch/QuantumCloudPlatform/issues/343
> fix: streamline authorization policy generation in lambda_handler

- backend/oqtopus_cloud/user/routers/jobs.py
- backend/tests/oqtopus_cloud/user/routers/test_jobs.py
- https://github.com/FujitsuResearch/QuantumCloudPlatform/issues/361
- Add a  process to delete S3 resources when SSE job is deleted using DELETE job API.
> feat: Add a process to delete S3 resources when SSE job is deleted. 

- backend/oas/provider/openapi.yaml
- backend/oas/provider/schemas/jobs.yaml
- backend/oas/user/openapi.yaml
- backend/oas/user/schemas/jobs.yaml
- backend/oqtopus_cloud/provider/schemas/jobs.py
- backend/oqtopus_cloud/user/schemas/jobs.py
- backend/tests/oqtopus_cloud/provider/routers/test_jobs.py
None.
This PR changes the OAS definition of the job transpile result so that the `stats` and  `virtual_physical_mappings` be JSON with arbitrary fields, not a string.
This is a breaking change, so after this PR is merged, current jobs with transpile_result will be never fetched through GET /jobs endpoint.
> feat: TranspileResult JSON

- docs/en/developer_guidelines/setup.md
> docs(setup): fix typo in setup command

- Makefile
- docs/en/developer_guidelines/setup.md
- docs/ja/developer_guidelines/setup.md
https://github.com/oqtopus-team/oqtopus-cloud/issues/191
The following commands were combined into `make setup-poetry`
- `poetry env use ~/.pyenv/shims/python`
- `poetry config virtualenvs.in-project true`
- `poetry install`
> feat: Combine poetry setup

- backend/oas/user/openapi.yaml
- backend/oas/user/paths/jobs.yaml
- backend/oqtopus_cloud/user/routers/jobs.py
- docs/oas/user/openapi.yaml
As it was requested to unify input for filtering jobs by id, name and description, I've added filtering by id via "q" URL query parameter
oqtopus-frontend pull request which unifies the mentioned input for filtering jobs
https://github.com/oqtopus-team/oqtopus-frontend/pull/84
> add support to filtering jobs by id

- .github/workflows/editorconfig-review.yaml
https://github.com/oqtopus-team/oqtopus-cloud/issues/242
I only added `-exclude '.*\.md$'` to make editorconfig-checker ignore md files.
> feat: make editorconfig-checker ignore markdown

- backend/oas/admin/openapi.yaml
- backend/oas/admin/paths/announcements.yaml
- backend/oas/user/openapi.yaml
- backend/oas/user/paths/announcements.yaml
- backend/oqtopus_cloud/admin/routers/announcements.py
- backend/oqtopus_cloud/user/routers/announcements.py
- backend/tests/oqtopus_cloud/admin/routers/test_announcements.py
- backend/tests/oqtopus_cloud/user/routers/test_announcements.py
- docs/oas/admin/openapi.yaml
- docs/oas/user/openapi.yaml
As discussed, updated Announcements API to enable filtering announcements by current_time query parameter. If it is provided, then the GET announcements request will return only those announcements which start_time is before current_time and end_time is after current_time
> add filtering announcements by optional current_time query parameter

- backend/oas/provider/openapi.yaml
- backend/oas/provider/paths/jobs.yaml
- backend/oqtopus_cloud/provider/routers/jobs.py
- backend/tests/oqtopus_cloud/provider/routers/test_jobs.py
- docs/oas/provider/openapi.yaml
#220 
renamed provider APIs `GET /jobs` parameter: max_results -> limit
> feat: renamed provider APIs `GET /jobs` parameter max_results -> limit

- backend/oqtopus_cloud/admin/routers/announcements.py
- backend/oqtopus_cloud/user/routers/announcements.py
- backend/oqtopus_cloud/user/routers/jobs.py
https://github.com/oqtopus-team/oqtopus-frontend/issues/112
In APIs that use pagination, when the value of the column we sort entities by is the same, then the order of retrieved entities cannot be guaranteed. Thus, we may encounter duplicates on the frontend from retrieving the same entities in different pages in pagination. To fix that, we have to add second sorting parameter (id), so that the database will always be able to determine the order the same way.
> Duplicate job display bug

- backend/oqtopus_cloud/provider/routers/jobs.py
This PR fixes: 
Currently, the query selecting jobs in the router of Provider API `GET /jobs`, the `order_by` clause is not specified 
and the resulting records' order will be undecidable.
> Fix : Add order_by clause to  select jobs query
