oqtopus-team/oqtopus-cloud

.github/git-pr-release.erb, .github/workflows/git-pr-release.yaml
=> [Enhancement]: Add git-pr-release

docs/en/developer_guidelines/openapi.md, docs/ja/architecture/sequence_diagram.md
=> docs:update openapi.md

CITATION.cff
=> chore: Update CITATION.cff

.github/git-pr-release.erb, .github/release.yaml
=> docs: update release note config

docs/README.ja.md, docs/README.md, docs/en/index.md, docs/ja/index.md
update doi badge that is latest one
you can check following link:
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.13677664.svg)](https://doi.org/10.5281/zenodo.13677664)
=> docs: update doi badge that is latest one

backend/oas/provider/openapi.yaml, backend/oas/provider/schemas/devices.yaml, backend/oas/provider/schemas/tasks.yaml, backend/oas/user/openapi.yaml, backend/oas/user/schemas/devices.yaml, backend/oas/user/schemas/tasks.yaml
Change date-time examples in oas files to with time zone (ISO 8601 format).
=> change date-time examples in oas files.

backend/tests/oqtopus_cloud/common/test_model_util.py, backend/tests/oqtopus_cloud/user/routers/test_devices.py, backend/tests/oqtopus_cloud/user/routers/test_tasks.py
Fix test code typos; "QPU" → "simulator".
=> Fix test code typos; QPU → simulator.

docs/en/operation/deployment.md, docs/ja/operation/deployment.md
Add terraform lock with DyanmoDB
=> docs: add terraform lock document

docs/oas/provider/openapi.yaml, docs/oas/user/openapi.yaml
update `docs/oas` related PR is #19
=> docs: update `docs/oas`

poetry.lock
=> chore: update poetry lock

docs/terraform_modules/api-server/README.md, terraform/service/example-dev/main.tf, terraform/service/modules/api-server/README.md, terraform/service/modules/api-server/main.tf, terraform/service/modules/api-server/variables.tf
add terraform module (lambda) environment variable
=> refactor: add lambda module environment variable

docs/en/developer_guidelines/faq.md, docs/ja/developer_guidelines/faq.md, terraform/infrastructure/example-dev/provider.tf, terraform/infrastructure/example-dev/variables.tf, terraform/service/example-dev/provider.tf
- Add document, how to execute terraform with mfa authentication
- Fixed terraform to explicitly specify profile
=> docs: add document, how to execute terraform with mfa authentication

backend/oas/user/openapi.yaml, backend/oas/user/paths/tasks.yaml, backend/oqtopus_cloud/user/routers/tasks.py, backend/tests/oqtopus_cloud/user/routers/test_tasks.py, docs/oas/user/openapi.yaml
The response codes when creating and deleting a task have been changed to 201 and 204, respectively.
=> refactor: change of response codes for creating and deleting tasks

.github/git-pr-release.erb, .github/workflows/update_version.yaml
This PR allow maintainer to ChatOps like updating version=x.y.z in `pyproject.toml`
you can update `pyproject.toml` via comment
=> ci: update version in `pyproject.toml`

deployment/oqtopus-dev/Makefile
- use uv as build process
- deploy process change
- `make deploy-all`
-  1min → 30s
=> chore: chore/build process uv

.github/workflows/python-ci.yaml
fix the path to the .coverage-xxx file.
incorrect path: `.coverage-xxx`
correct path: `./backend/.coverage-xxx`
=> fix: fix the path to the .coverage-xxx file

deployment/oqtopus-dev/Makefile
=> chore: fix zip command

terraform/service/modules/api-server/main.tf
[#274](https://github.com/FujitsuResearch/QuantumCloudPlatform/issues/274)
Enabled Lambda SnapStart. Updated "terraform/service/modules/api-server/main.tf".
=> feat: Lambda SnapStart enabled (from: None to: PublishedVersions)

docs/en/operation/deployment.md, docs/ja/operation/deployment.md
[#289](https://github.com/FujitsuResearch/QuantumCloudPlatform/issues/289)
update org from "example" to "oqtopus" (deployment.md)
=> chore: update org from "example" to "oqtopus"

docs/oas/provider/openapi.yaml, docs/oas/user/openapi.yaml
=> docs: update oas

backend/oas/provider/openapi.yaml, backend/oas/provider/paths/devices.yaml, backend/oas/provider/paths/jobs.yaml, backend/oas/provider/root.yaml, docs/oas/provider/openapi.yaml
Add SecuritySchema to OpenAPI spec of ProviderAPI.
Enable ApiKeyAuth for every ProviderAPI endpoints.
=> feat: Provider API security auth

backend/README.md
Add simple backend startup scripts.
=> docs: add run scripts

backend/oas/provider/openapi.yaml, backend/oas/provider/paths/jobs.yaml, docs/oas/provider/openapi.yaml
=> fix: Add security tag in patch job info

backend/oas/provider/openapi.yaml, backend/oas/provider/schemas/jobs.yaml, backend/oqtopus_cloud/provider/schemas/jobs.py, docs/oas/provider/openapi.yaml
=> fix: Add nullable to EstimationResult

backend/oas/user/openapi.yaml, backend/oas/user/paths/jobs.yaml, backend/oqtopus_cloud/user/routers/jobs.py, backend/tests/oqtopus_cloud/user/routers/test_jobs.py, docs/oas/user/openapi.yaml
https://github.com/FujitsuResearch/QuantumCloudPlatform/issues/298
mofify `startTime` and `endTime` to snake_case
https://github.com/oqtopus-team/oqtopus-cloud/blob/7cf15730130b88792808397344061b4cd26869c9/backend/oas/user/openapi.yaml#L98-L136
=> refactor: modify startTime and endTime to snake_case

backend/oqtopus_cloud/provider/routers/jobs.py, backend/tests/oqtopus_cloud/provider/routers/test_jobs.py
- https://github.com/FujitsuResearch/QuantumCloudPlatform/issues/282
Set the datetime field when update job status.
=> feat: Set the datetime when update job status

backend/oqtopus_cloud/provider/routers/jobs.py, backend/tests/oqtopus_cloud/provider/routers/test_jobs.py
Make Provider API apply execution time in the handler of `PATCH /jobs/:job_id/job_info`
=> fix: ProviderAPI: Update execution time

backend/oas/provider/openapi.yaml, backend/oas/provider/paths/jobs.yaml, backend/oas/provider/root.yaml, backend/oas/provider/schemas/jobs.yaml, backend/oas/user/openapi.yaml, backend/oas/user/paths/jobs.yaml, backend/oas/user/root.yaml, backend/oas/user/schemas/jobs.yaml, backend/oqtopus_cloud/common/models/job.py, backend/oqtopus_cloud/provider/routers/jobs.py, backend/oqtopus_cloud/provider/schemas/jobs.py, backend/oqtopus_cloud/user/routers/jobs.py, backend/oqtopus_cloud/user/schemas/jobs.py, backend/tests/oqtopus_cloud/provider/conftest.py, backend/tests/oqtopus_cloud/provider/routers/test_jobs.py, backend/tests/oqtopus_cloud/user/conftest.py, backend/tests/oqtopus_cloud/user/routers/test_jobs.py, poetry.lock, pyproject.toml
- https://github.com/FujitsuResearch/QuantumCloudPlatform/issues/288
- Add codes and schemas for SSE and multi programing manual
=> Feature/#288 add SSE and MP manual

backend/oas/admin/openapi.yaml, backend/oas/admin/paths/devices.yaml, backend/oas/admin/paths/users.yaml, backend/oas/admin/paths/whitelist_users.yaml, backend/oas/provider/openapi.yaml, backend/oas/provider/paths/devices.yaml, backend/oas/provider/paths/hello.yaml, backend/oas/provider/paths/jobs.yaml, backend/oas/provider/root.yaml, backend/oas/user/openapi.yaml, backend/oas/user/paths/api-token.yaml, backend/oas/user/paths/devices.yaml, backend/oas/user/paths/jobs.yaml, backend/oas/user/root.yaml, backend/oas/user_signup/openapi.yaml, backend/oas/user_signup/paths/confirm_signup.yaml, backend/oas/user_signup/paths/mfa_reset_request.yaml, docs/oas/admin/openapi.yaml, docs/oas/provider/openapi.yaml, docs/oas/user/openapi.yaml
=> refactor: Modify casing of OAS operation id

docs/oas/user/openapi.yaml, terraform/service/oqtopus-dev/main.tf
Make User API allow Q-API-TOKEN header in cross-origin access.
=> bugfix: Make UserAPI allow q-api-token header

backend/oqtopus_cloud/user/routers/jobs.py, backend/tests/oqtopus_cloud/user/routers/test_jobs.py
=> hotfix : UserAPI get_jobs

backend/oas/provider/openapi.yaml, backend/oas/provider/paths/jobs.yaml, backend/oas/provider/root.yaml, backend/oas/provider/schemas/jobs.yaml, backend/oqtopus_cloud/provider/routers/jobs.py, backend/oqtopus_cloud/provider/schemas/jobs.py, backend/tests/oqtopus_cloud/provider/routers/test_jobs.py
Enable providers to update jobs `transpiler_info`.
This PR does not bring any breaking change.
=> Feat : ProviderAPI update jobs' transpiler_info endpoint

backend/oas/provider/openapi.yaml, backend/oas/provider/schemas/jobs.yaml, backend/oas/user/openapi.yaml, backend/oas/user/paths/jobs.yaml, backend/oas/user/schemas/jobs.yaml, backend/oqtopus_cloud/provider/schemas/jobs.py, backend/oqtopus_cloud/user/schemas/jobs.py, backend/tests/oqtopus_cloud/provider/routers/test_jobs.py
The estimation jobs' `operator` parameter has been changed:
- now `coeff` param is a real number.
=> feat : OAS change estimation jobs operator coefficient to real

backend/oas/provider/openapi.yaml, backend/oas/provider/schemas/jobs.yaml, backend/oas/user/openapi.yaml, backend/oas/user/schemas/jobs.yaml, backend/oqtopus_cloud/provider/schemas/jobs.py, backend/oqtopus_cloud/user/schemas/jobs.py, backend/tests/oqtopus_cloud/provider/routers/test_jobs.py
- The estimation job result type has been changed:
- exp_value has been a real number
=> feat: Estimation jobs result has been changed

pyproject.toml
https://github.com/FujitsuResearch/QuantumCloudPlatform/issues/367
fix pydantic version 0.4.1 to ^2.1
https://github.com/oqtopus-team/oqtopus-cloud/pull/158
=> fix: pydantic version fixed

terraform/service/modules/api-server/main.tf, terraform/service/modules/lambda-auth/main.tf
https://github.com/FujitsuResearch/QuantumCloudPlatform/issues/360
Add lambda:TagResource to lambda functions
=> feat: #360 add tag resource permission

backend/oqtopus_cloud/lambda_auth/lambda_function.py, backend/tests/oqtopus_cloud/lambda_auth/routers/test_lambda_function.py
Fixed lambda-authorizer so that deny when the user's status is suspended or unapproved.
=> fix: add user suspend

.github/workflows/update-poetry-lock.yaml
https://github.com/FujitsuResearch/QuantumCloudPlatform/issues/366
update-poetry-lock.yaml added.
This workflow updates poetry.lock automatically.
Without PR
https://github.com/oqtopus-team/oqtopus-cloud/actions/runs/13810539043/job/38630915353
=> feat: Create update poetry.lock action

docs/en/developer_guidelines/setup.md
https://github.com/FujitsuResearch/QuantumCloudPlatform/issues/354
Change python version 3.12.4 -> 3.12.3
=> chore: python version fixed

.github/workflows/deployment.yaml
https://github.com/FujitsuResearch/QuantumCloudPlatform/issues/374
Improved notification text.
=> feat: improved notification text

.github/workflows/update-poetry-lock.yaml
https://github.com/FujitsuResearch/QuantumCloudPlatform/issues/372
Added user.name and user.email.
=> fix: add git configs

backend/oqtopus_cloud/provider/routers/devices.py
=> fix: Fix the issue-195

docs/en/architecture/frontend_authentication_flow.md, docs/en/architecture/frontend_signup_signin_flow.md
None
This Pull Request is to modify the sequence diagrams to match the current implementation
- fix english expression for the sequence diagrams
- add description of user status validation process
- https://github.com/oqtopus-team/oqtopus-cloud/pull/165
=> fix: update terminology in authentication and signup flow documentation

.github/workflows/deployment.yaml, deployment/oqtopus-dev/Makefile
#194
- Add AWS_ACCOUNT_ID to the env.
- Use AWS_DEFAULT_REGION
- Improve error logging
=> fix: #194 auto deployment failed

scripts/setup_aqua.sh
https://github.com/oqtopus-team/oqtopus-cloud/issues/206
Fixed aqua version to v2.48.1
=> fix: "Update document" failed

.gitignore, terraform/infrastructure/oqtopus-dev/Makefile, terraform/infrastructure/oqtopus-prod/Makefile, terraform/service/oqtopus-dev/Makefile, terraform/service/oqtopus-prod/Makefile
#209 
Added diffs.ansi on `make plan`
=> feat: #209 output diffs.ansi

.github/workflows/actionlint.yaml
https://github.com/FujitsuResearch/QuantumCloudPlatform/issues/312
I only added "reviewdog/action-actionlint" to use it for action linter
=> feat: create actionlint workflow

backend/oas/admin/openapi.yaml, backend/oas/admin/paths/users.yaml, backend/oqtopus_cloud/admin/routers/users.py, backend/tests/oqtopus_cloud/admin/routers/test_users.py, docs/oas/admin/openapi.yaml
Implemented GET /users/{user_id}, which allows to retrieve specific user by their id.
=> add API to GET specific user by id

README.md, docs/en/index.md, docs/ja/index.md
Update the Slack link in the documentation to ensure users can join the workspace correctly.
=> Fix Slack link in documentation
